version: '2'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:  
      - "8000"
    volumes:
      - .:/app/:cached
      - ./database:/database.db
      - ./inputfiles:/inputfiles
      - ./modelfiles:/modelfiles
      - ./outputfiles:/outputfiles
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`localhost`)
      - traefik.http.services.backend.loadbalancer.server.port=8000
      - traefik.http.routers.backend.tls=true
      - traefik.http.routers.backend.tls.certresolver=letsencrypt
  
  traefik-backend:
    build:
      context: .
      dockerfile: Dockerfile.traefik
    ports:
      - "36554:80"
      - "36555:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-public-certificates:/certificates
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`dashboard.localhost`)
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.tls.certresolver=letsencrypt
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.users=testuser:$$apr1$$jIKW.bdS$$eKXe4Lxjgy/rH65wP1iQe1

volumes:
  traefik-public-certificates: