FROM python:3.7.7

WORKDIR /fmdeploy_backend

RUN pip install --upgrade pip

COPY ./requirements.txt /fmdeploy_backend/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /fmdeploy_backend/requirements.txt

COPY ./app /fmdeploy_backend/app

EXPOSE 8000

RUN apt-get update -y && apt-get install -y --no-install-recommends build-essential gcc \libsndfile1 

RUN apt-get -y install libsndfile1

RUN apt-get -y install ffmpeg

CMD ["gunicorn", "-k", "uvicorn.workers.UvicornH11Worker", "app.main:app", "-b 0.0.0.0:8000"]