
services:
  # MySQL
  db:
    container_name: "db"
    build: ./docker/mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: fmdeploy_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 2f2kir2y49xy6g 
      MYSQL_ROOT_PASSWORD: 2f2kir2y49xy6g 
    ports:
      - 3307:3306
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql 
    networks:
      - local-net

  api:
    links:
        - db
    container_name: "api"
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./code:/usr/src/server
    networks:
      - local-net
    ports:  
      - 8000:8000

networks:
  local-net:
    driver: bridge